"""
Daily Digest Generator — builds maintainer-focused summary reports.
Output: Markdown, Slack, or Discord formatted digest.
"""

from dataclasses import dataclass
from datetime import datetime, timedelta
from typing import Optional

import structlog
from jinja2 import Environment, BaseLoader

from src.core.analyzer import TriageReport, PRAnalysisResult, IssueAnalysisResult

logger = structlog.get_logger(__name__)


DIGEST_TEMPLATE = """
# 📋 Triage Digest — {{ repo }}
**Generated:** {{ date }} | **Period:** Last 24 hours

---

## 🚨 Critical Items (Action Required Today)
{% if critical_prs %}
{% for pr in critical_prs %}
- **PR #{{ pr.pr.number }}** — [{{ pr.pr.title }}]({{ pr.pr.url }})
  - Priority: `{{ pr.classification.priority }}` | Type: `{{ pr.classification.type }}` | Quality: {{ pr.quality_score.emoji }} {{ pr.quality_score.tier }}
  - Author: @{{ pr.pr.author }} | Changes: +{{ pr.pr.additions }}/-{{ pr.pr.deletions }}
{% endfor %}
{% else %}
✅ No critical items today.
{% endif %}

---

## 👀 Ready for Review (High Quality PRs)
{% if excellent_prs %}
{% for pr in excellent_prs %}
- **PR #{{ pr.pr.number }}** — [{{ pr.pr.title }}]({{ pr.pr.url }})
  - Score: **{{ pr.quality_score.overall }}/100** | Type: `{{ pr.classification.type }}`
  - Author: @{{ pr.pr.author }} | {{ pr.pr.files_changed | length }} files changed
{% endfor %}
{% else %}
_No high-quality PRs awaiting review._
{% endif %}

---

## ⚠️ Flagged Items (AI Slop / Low Quality)
{% if flagged_prs %}
{% for pr in flagged_prs %}
- **PR #{{ pr.pr.number }}** — [{{ pr.pr.title }}]({{ pr.pr.url }})
  - Confidence: {{ "%.0f" | format(pr.slop_result.confidence * 100) }}% | Severity: `{{ pr.slop_result.severity }}`
  - Signals: {{ pr.slop_result.signal_names[:3] | join(', ') }}
  - Author: @{{ pr.pr.author }}
{% endfor %}
{% else %}
✅ No flagged items.
{% endif %}

---

## 🔍 Duplicate Issues Closed
{% if duplicate_issues %}
{% for issue in duplicate_issues %}
- **Issue #{{ issue.issue.number }}** — {{ issue.issue.title }}
  - Duplicate of: #{{ issue.duplicate_of }}
  - Author: @{{ issue.issue.author }}
{% endfor %}
{% else %}
_No duplicate issues detected._
{% endif %}

---

## 📊 Summary Stats
| Metric | Count |
|--------|-------|
| PRs Analyzed | {{ stats.total_prs_analyzed }} |
| Issues Analyzed | {{ stats.total_issues_analyzed }} |
| Critical PRs | {{ stats.critical_prs }} |
| Slop Flagged | {{ stats.slop_flagged }} |
| Excellent Quality | {{ stats.excellent_quality }} |
| Duplicate Issues | {{ stats.duplicate_issues }} |
| Avg Quality Score | {{ stats.avg_quality_score }}/100 |

---
_Generated by [PR Triage Bot](https://github.com/your-org/pr-triage-bot)_
""".strip()


class DigestGenerator:
    """
    Generates daily maintainer digests from triage reports.
    Supports multiple output formats.
    """

    def __init__(self):
        self.env = Environment(loader=BaseLoader())

    def generate(
        self,
        report: TriageReport,
        format: str = "markdown",
    ) -> str:
        """
        Generate a digest from a triage report.
        format: "markdown" | "slack" | "discord"
        """
        logger.info(
            "Generating digest",
            repo=report.repo,
            prs=len(report.pr_results),
            format=format,
        )

        if format == "markdown":
            return self._render_markdown(report)
        elif format == "slack":
            return self._render_slack(report)
        elif format == "discord":
            return self._render_discord(report)
        else:
            raise ValueError(f"Unknown format: {format}")

    def _render_markdown(self, report: TriageReport) -> str:
        """Render full markdown digest."""
        template = self.env.from_string(DIGEST_TEMPLATE)
        return template.render(
            repo=report.repo,
            date=report.generated_at.strftime("%Y-%m-%d %H:%M UTC"),
            critical_prs=report.critical_prs[:10],
            excellent_prs=report.excellent_prs[:10],
            flagged_prs=report.flagged_prs[:10],
            duplicate_issues=report.duplicate_issues[:10],
            stats=report.stats,
        )

    def _render_slack(self, report: TriageReport) -> str:
        """Render Slack-formatted digest (plain text with emoji)."""
        lines = [
            f"📋 *Triage Digest — {report.repo}*",
            f"_{report.generated_at.strftime('%Y-%m-%d')} | {len(report.pr_results)} PRs, {len(report.issue_results)} Issues_",
            "",
        ]

        if report.critical_prs:
            lines.append(f"*🚨 Critical ({len(report.critical_prs)}):*")
            for pr in report.critical_prs[:5]:
                lines.append(f"  • <{pr.pr.url}|PR #{pr.pr.number}>: {pr.pr.title[:60]}")
            lines.append("")

        if report.flagged_prs:
            lines.append(f"*⚠️ Flagged ({len(report.flagged_prs)}):*")
            for pr in report.flagged_prs[:5]:
                lines.append(f"  • <{pr.pr.url}|PR #{pr.pr.number}>: {pr.pr.title[:60]}")
            lines.append("")

        stats = report.stats
        lines.append(
            f"*Stats:* {stats['total_prs_analyzed']} PRs | "
            f"{stats['slop_flagged']} flagged | "
            f"{stats['excellent_quality']} excellent | "
            f"Avg score: {stats['avg_quality_score']}/100"
        )

        return "\n".join(lines)

    def _render_discord(self, report: TriageReport) -> str:
        """Render Discord-formatted digest."""
        # Discord uses markdown but with different embed style
        lines = [
            f"## 📋 Triage Digest — `{report.repo}`",
            f"> {report.generated_at.strftime('%Y-%m-%d %H:%M UTC')}",
            "",
        ]

        if report.critical_prs:
            lines.append(f"### 🚨 Critical PRs")
            for pr in report.critical_prs[:5]:
                lines.append(f"- **#{pr.pr.number}** [{pr.pr.title[:60]}]({pr.pr.url})")
            lines.append("")

        if report.flagged_prs:
            lines.append(f"### ⚠️ Flagged PRs")
            for pr in report.flagged_prs[:5]:
                lines.append(f"- **#{pr.pr.number}** [{pr.pr.title[:60]}]({pr.pr.url})")
            lines.append("")

        stats = report.stats
        lines.extend([
            "### 📊 Stats",
            "```",
            f"PRs Analyzed:    {stats['total_prs_analyzed']}",
            f"Slop Flagged:    {stats['slop_flagged']}",
            f"Critical:        {stats['critical_prs']}",
            f"Avg Quality:     {stats['avg_quality_score']}/100",
            "```",
        ])
        return "\n".join(lines)